# These are supported funding model platforms

github: [ForbesLindesay]
patreon: ForbesLindesay
open_collective: # Replace with an open collevite username
ko_fi: # Replace with a single Ko-fi username
tidelift: # npm/@forbeslindesay/npm-package-template
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with a single custom sponsorship URL
